### ISSUE TITLE
Issue with no such device or address

### ISSUE THREAD

**Issue by troydieter** [issafram/vault-credential-rotator#2]
When executing:

`dotnet run`

receiving the following:

```
tdieter@FS000PPRLW13390:/coderepo/vault-credential-rotator/src/VaultCredentialRotator$ dotnet run
Vault Credential Rotator - Version 1.0.0
Created by Issa Fram

Username: tdieter
Password: **********

Unhandled Exception: System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at VaultCredentialRotator.Program.GetClientTokenHttpResponseMessageAsync(String getClientTokenUri, String json) in /mnt/c/coderepo/vault-credential-rotator/src/VaultCredentialRotator/Program.cs:line 115
   at VaultCredentialRotator.Program.Main(String[] args) in /mnt/c/coderepo/vault-credential-rotator/src/VaultCredentialRotator/Program.cs:line 58
   at VaultCredentialRotator.Program.<Main>(String[] args)
```

I have the following in my appsettings.json:
```

{
  "AWS": {
    "BaseClientTokenUri": "https://REDACTED.com/v1/auth/ldap/login/",
    "BaseCredentialsUri": "http://REDACTED.com/v1/aws/creds/",
    "Roles": [
    "grp-aws-r-REDACTED-powerusers"
    ]
  }
}
```

**Comment by troydieter** [comment]
This is ran from Windows Subsystem for Linux 1:

```
tdieter@FS000PPRLW13390:/coderepo/vault-credential-rotator/src/VaultCredentialRotator$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by troydieter** [comment]
Resolved by adding certificate chain to store.
